### PR TITLE
Adds code completion

### PR DESCRIPTION
**Pull request by dylon**
Major changes:
1. Adds support for code completion with definition previews.
2. Minor bug fixes:
    1. Fixes error where client main script pointed to the wrong location (issue with development artifacts).
    2. Renames the configuration from `"Example configuration"` to `"LFortran Language Server"` (visible in VSCode's settings).
    3. Decrements the column offsets from lfortran by one for correctness.

Notes:
1. Prefix tries are used to index terms for code completion.
2. The final nodes of the prefix tries, representing ending characters of completion terms, map to values of type `CompletionItem` so lookups can be performed quickly.
3. These indices will be used for hover previews and anywhere else they are useful.
4. VSCode does its own filtering atop whatever we return for code completion, so our `onCompletion` handler is not always guaranteed to be called and it is not guaranteed that all the results we return will be presented to the user for completion.
5. We can force VSCode to always call our `onCompletion` handler on keystrokes but cannot prevent it from post-processing (filtering) our results.

### CODE REVIEW

**Review by certik — APPROVED** [review]
I haven't tested it, but I think we can merge it.

Should we add some CI soon?

**Comment by dylon** [comment]
> I haven't tested it, but I think we can merge it.
> 
> Should we add some CI soon?

Yes, I'll add support for displaying symbol definitions when they are hovered over with the mouse, because most of the related work has been completed as part of this PR, and then I will add a CI testing suite. I can probably get them both done tomorrow or Wednesday at the latest.

**Comment by certik** [comment]
Go ahead and merge this PR as you see fit.

**Review by Pranavchiku — APPROVED** [review]
I tested locally, this works. Merging this and will be opening PR with instructions to build.

**Pull request merged**
