### PR TITLE
Improves tracing of function calls; improves logging of LFortran errors

### PR DESCRIPTION
**Pull request by dylon**
Addresses concerns in the following issues:
- https://github.com/lfortran/lfortran-lsp/issues/34
- https://github.com/lfortran/lfortran-lsp/issues/22

### CODE REVIEW

**Comment by certik** [comment]
I think it looks good. The CI has to be fixed.

**Comment by dylon** [comment]
> I think it looks good. The CI has to be fixed.

The CI extension that runs the integration tests occasionally fails on its clean-up step:

```
/usr/bin/bash /home/runner/work/_actions/coactions/setup-xvfb/v1/dist/cleanup.sh
/usr/bin/bash: /home/runner/work/_actions/coactions/setup-xvfb/v1/dist/cleanup.sh: No such file or directory
Error: The process '/usr/bin/xvfb-run' failed with exit code 3
```

The solution for this failure is to re-run the integration tests.

**Comment by dylon** [comment]
And, the integration tests failed again on the extension's clean-up step ... If this continues to happen, I will need to find an alternative. It fails too often.

**Comment by Pranavchiku** [comment]
Is this good to merge?

**Comment by certik** [comment]
I think so.

**Pull request merged**
